### ISSUE TITLE
Constraint the usage of t.modify to implemented interfaces fields

### ISSUE THREAD

**Issue by jderrough** [prisma-labs/nexus#251] opened 2019-10-07 08:57 UTC
Even though `t.modify` is intended to override fields defined by implemented interfaces ([documentation](https://nexus.js.org/docs/api-interfacetype) & [code](https://github.com/prisma-labs/nexus/blob/develop/src/builder.ts#L721)), the example below is considered valid by the compiler:

```javascript
const Query = queryType({
    definition(t) {
        t.crud.users();
        t.modify('users', { resolve: () => [] });
    },
});
```

Constraining the usage of `t.modify` would greatly help avoiding making that mistake.

**Comment by tgriesser** [comment] 2019-11-07 22:21
Closing, since this API is now removed in 0.12.0 since as you mention, it was quite a confusing API that wasn't super useful (not sure if it even ever worked as intended).

**Closed by tgriesser** 2019-11-07 22:21 UTC
